"""Initial migration

Revision ID: e14f5ddde47d
Revises: 
Create Date: 2026-01-09 13:37:24.008571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e14f5ddde47d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_events',
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_alert', sa.Boolean(), nullable=True),
    sa.Column('alert_type', sa.Text(), nullable=True),
    sa.Column('alert_level', sa.Text(), nullable=True),
    sa.Column('alert_title', sa.Text(), nullable=True),
    sa.Column('alert_message', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anomaly_events')
    # ### end Alembic commands ###
